apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backstage-app
  description: An example of a Backstage application.
spec:
  type: website  # or 'url', depending on what you intend
  owner: john@example.com
  lifecycle: experimental
  target: /app/templates/my-template.yaml
